# Generated by Django 3.2.9 on 2021-11-23 10:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCRCamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('location', models.CharField(max_length=50, verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Câmera OCR',
                'verbose_name_plural': 'Câmeras OCR',
            },
        ),
        migrations.CreateModel(
            name='OCRCameraAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('alert_date', models.DateTimeField(verbose_name='Data/Hora')),
                ('plate', models.CharField(max_length=7, verbose_name='Placa')),
                ('description', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Câmera OCR - Alerta',
                'verbose_name_plural': 'Câmeras OCR - Alertas',
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('sector', models.CharField(max_length=10, verbose_name='Setor')),
                ('type', models.IntegerField(choices=[(1, 'Normal'), (2, 'Preferencial')], default=1, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='Unity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('location', models.CharField(blank=True, max_length=500, null=True, verbose_name='Localidade')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.CreateModel(
            name='SpaceEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('event_date', models.DateTimeField(verbose_name='Data/Hora')),
                ('type', models.IntegerField(choices=[(1, 'Ocupado'), (2, 'Livre')], default=1, verbose_name='Tipo')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.space', verbose_name='Vaga')),
            ],
            options={
                'verbose_name': 'Vaga - Evento',
                'verbose_name_plural': 'Vaga - Eventos',
            },
        ),
        migrations.CreateModel(
            name='SpaceAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('alert_date', models.DateTimeField(verbose_name='Data/Hora')),
                ('description', models.CharField(max_length=50, verbose_name='Descrição')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.space', verbose_name='Vaga')),
            ],
            options={
                'verbose_name': 'Vaga - Alerta',
                'verbose_name_plural': 'Vagas - Alertas',
            },
        ),
        migrations.AddField(
            model_name='space',
            name='unity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.unity', verbose_name='Unidade'),
        ),
        migrations.CreateModel(
            name='OCRCameraEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('event_date', models.DateTimeField(verbose_name='Data/Hora')),
                ('plate', models.CharField(max_length=7, verbose_name='Placa')),
                ('type', models.IntegerField(choices=[(1, 'Entrada'), (2, 'Livre')], default=1, verbose_name='Tipo')),
                ('cameraOCR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.ocrcamera', verbose_name='Câmera OCR')),
            ],
            options={
                'verbose_name': 'Câmera OCR - Evento',
                'verbose_name_plural': 'Câmeras OCR - Eventos',
            },
        ),
        migrations.AddField(
            model_name='ocrcamera',
            name='unity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.unity', verbose_name='Unidade'),
        ),
    ]
