# Generated by Django 3.2.9 on 2021-11-23 21:11

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20211123_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('plate', models.CharField(max_length=7, verbose_name='Placa')),
                ('status', models.IntegerField(choices=[(1, 'Dentro'), (2, 'Fora')], default=1, verbose_name='Situação')),
                ('enter_date', models.DateTimeField(verbose_name='Entrada')),
                ('exit_date', models.DateTimeField(blank=True, null=True, verbose_name='Saída')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='space',
            name='status',
            field=models.IntegerField(choices=[(1, 'Livre'), (2, 'Ocupada')], default=1, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='spaceevent',
            name='type',
            field=models.IntegerField(choices=[(1, 'Livre'), (2, 'Ocupado')], default=1, verbose_name='Tipo'),
        ),
    ]
