# Generated by Django 3.2.9 on 2021-11-23 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_auto_20211123_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name': 'Visitante', 'verbose_name_plural': 'Visitantes'},
        ),
        migrations.AddField(
            model_name='visitor',
            name='unity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parking.unity', verbose_name='Unidade'),
            preserve_default=False,
        ),
    ]
