# Generated by Django 3.2.9 on 2021-11-24 16:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_auto_20211123_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('plate', models.CharField(max_length=7, verbose_name='Placa')),
                ('expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de validade')),
                ('description', models.CharField(max_length=50, verbose_name='Descrição')),
                ('unity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.unity', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Restrições',
                'verbose_name_plural': 'Restrições',
            },
        ),
    ]
